[ethereum]
    serverPort = 9999
    rpcURL = "https://eth-goerli.g.alchemy.com/v2/Yy5Huxu5D7mM0_BigYQzKoiPVCxBw69p"
    contractAddr = "0x459028083482ac4c9691ebbcc443a19e9613fd87"
    cryFile = "/www/server/panel/vhost/letsencrypt/www.naughtygr.com/fullchain.pem"
    keyFile = "/www/server/panel/vhost/letsencrypt/www.naughtygr.com/privkey.pem"