[ethereum]
    serverPort = 9999
    rpcURL = "https://eth-mainnet.g.alchemy.com/v2/BrMLCM-FKjsQi0anbthKgECWYtPJ7mPY"
    contractAddr = "0x459028083482ac4c9691ebbcc443a19e9613fd87"
    cryFile = "./fullchain.pem"
    keyFile = "./privkey.pem"
    beginIndex = 4000